name: CI
on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main]
jobs:
  run-ci:
    name: Run CI Python
    uses: ./.github/workflows/_resauable-python-ci.yml
    with:
      python_version: 3.11
      working_directory: app
    secrets: 
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
  notify:
    needs: [run-ci]
    runs-on: ["self-hosted","Linux","X64"]
    steps:
      - name: Show output return from resauable file
        run: |
         echo "Coverage: ${{ needs.run-ci.outputs.coverage-pct }}"
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
          retention-days: 1



      